### ISSUE TITLE
Removing tables_demo_bringup as exec depend 

### ISSUE THREAD

**Issue by jarkenau** [DFKI-NI/grasplan#22]
By having a dependency on the `tables_demo_bringup` package a circular dependency is introduced into the mobipick_labs environment. 

Currently it is only used to get the related planning scene `yaml` files,  in the following locations:

```bash 
launch/planning_scene/planning_scene_visualization.launch:5:  <arg name="yaml_path_to_read" default="$(find tables_demo_bringup)/config/$(arg world_config)_planning_scene.yaml" />
launch/planning_scene/find_planning_scene_boxes_helper.launch:7:  <arg name="yaml_path_to_read" default="$(find tables_demo_bringup)/config/$(arg world_config)_planning_scene.yaml" />
launch/planning_scene/find_planning_scene_boxes_helper.launch:8:  <arg name="yaml_path_to_write" default="$(find tables_demo_bringup)/config/$(arg world_config)_planning_scene.yaml" />
```

output of `grep -rn -e "tables_demo_bringup"`

@oscar-lima any idea on how should approach this?

**Comment by oscar-lima** [comment]
we could point to example config files within grasplan ros pkg, e.g. https://github.com/DFKI-NI/grasplan/tree/noetic/config/examples
