### ISSUE TITLE
Move planning scene utilities into separate repository

### ISSUE THREAD

**Issue by jarkenau** [DFKI-NI/grasplan#25]
The planning scenes are a requirement for grasplan due to MoveIt!. To continue the clean up of this repository, I would propose to create another repository with all your utilities to create new planning scenes (would mainly include the rqt_gui from @oscar-lima). I could imagine something like `planning_scene_helpers`.

**Comment by oscar-lima** [comment]
As discussed in person (Julian and I) we will delete the Grasplan GUI that allows to modify yaml planning scenes and go with the approach of editing planning scenes using RViz MotionPlanning MoveIt plugin, see issue: https://github.com/DFKI-NI/grasplan/issues/26
